services:
  postgres:
    image: postgres:15
    container_name: smarttask-postgres
    restart: always
    environment:
      POSTGRES_DB: smart_task_db
      POSTGRES_USER: smart_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: smarttask-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "/+fTXuozAGnCpV4uxWMKx9ZGeV6diZcfgbZ+boY/fSA="

      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d813mdpkh4rs73ea2i8g-a:5432/smart_task_db_8xq9
      SPRING_DATASOURCE_USERNAME: smart_task_api
      SPRING_DATASOURCE_PASSWORD: 0RllmusVD2cvgWsPEasTYxM7uvYgoM0r

#      JWT_SECRET=/+fTXuozAGnCpV4uxWMKx9ZGeV6diZcfgbZ+boY/fSA=
#      JWT_EXPIRATION=86400000

#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smart_task_db
#      SPRING_DATASOURCE_USERNAME: smart_user
#      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: